const paragraph = [
    'Timothy Treadwell spent 13 summers living with grizzly bears in remote Alaska. He loved them and gave them cute pet names like Mr. Chocolate. These wild animals were anything but cute. Weighing up to 1,700 pounds and standing up to 7 feet tall, these animals were dangerous. Treadwell wasn’t afraid, though. He claimed he was an “accepted wild animal and brother to these bears.” The grizzlies begged to differ. They tolerated his presence but ultimately killed him.',
    'In 1900, a British medical journal reported that some Russian peasants from the northeastern Pskov region had a unique method of dealing with harsh winters and scarce food. When the snow came they would go inside, light the stove and fall into a deep sleep. They called this state “lotska.” They would wake briefly just once a day to eat some hard bread and drink some water before returning to sleep. Six months later, when spring arrived, they would resume their normal lives.',
    'This past New Year’s Eve, a 64-year-old Michigan man took a fall that almost cost him his life. At 10:30 pm, Bob took a break from watching football on TV and stepped outside. He was going to get wood for the fire when he slipped on some icy steps. As he lay in the snow, without a jacket, he knew that he was in serious trouble. He had broken his neck and couldn’t move. Bob’s wife was visiting her parents, and he was all alone. He screamed for help, but his nearest neighbor was far away. No one heard him except for his loyal dog Kelsey.',
    'She originally started her research into posture after having back pain herself as a young mother. She described her pain as excruciating. She couldn’t sleep at night and couldn’t even pick up her baby. After getting surgery, she got some relief, but the pain returned. After hearing she would need surgery again, she knew the answer was not conventional medicine. She needed to think outside the box. After reading medical studies showing that traditional cultures didn’t have these modern problems, she decided to study them firsthand. She traveled the world, exploring villages from Africa to Ecuador, studying how people stood, sat, moved, and worked. Despite having very physically demanding lives, they were mostly pain-free.',
    'in 2007, the movie Bucket List, starring Jack Nicholson and Morgan Freeman, popularized the idiom. It’s about two older men who are dying and go on a road trip to do all the things on their bucket list. Their list included skydiving, visiting the Taj Mahal, and riding motorcycles along the Great Wall of China. The movie got mixed reviews, but the expression struck a chord with people. Even people who have never seen the movie now know and use this idiom.',
    'While Jackson was famous for burning through money, some people have been known to actually burn money. Cocaine kingpin, Pablo Escobar, was at one time the 7th richest man in the world and was making 420 million dollars a week. Like Jackson, he was also a big spender with lavish houses and his own personal zoo. The final year of his life was spent on the run from police after escaping from prison. During this time, he once burned 2 million dollars in cash to make a fire to warm his daughter.',
    'Lawrence Ripple entered the bank and gave the teller a note that said, “I have a gun, give me money.” Ripple didn’t have a gun, and strangely, he didn’t actually want the money. After the teller handed over $3,000 in cash, Ripple sat down in the lobby and waited for the cops to come. This didn’t take long since Ripple chose a bank with a police station on the same block.',
    'After boarding each merchant ship, they’d take everyone prisoner and then sink the ship. It was at this point that von Luckner got his reputation for being a gentleman pirate. He had outfitted his boat with 400 bunks for his prisoners and spacious rooms for the captured captains and officers. He even had special dining rooms outfitted with French and English magazines and books and a gramophone with the latest music.',
    'Earlier this year, 50-year-old Edgar Latulip was found. Suddenly after 30 years of living in the dark, he started having flashbacks of his former life. The name Edgar Latulip popped into his head, and he thought it might be his. He told a friend who Googled it, and sure enough, a man named Edgar Latulip had gone missing 30 years before. After taking a DNA test, the police confirmed his identity.',
    'Yoshifumi Miyazaki of Chiba University studied the effects of nature on stress. He organized two groups of volunteers. Eighty-four of them walked in nature, and eighty-four of them walked in a city. After just a 15-minute walk, the nature walkers demonstrated lower levels of stress. Their blood pressure fell by 2 percent, their heart rate decreased by 4 percent, and their levels of cortisol, a stress hormone, dropped by 16 percent. Miyazaki thinks that humans have evolved to be more relaxed in nature.',
]